Parameters:
  BucketName:
    Type: String
    Description: "The name of the S3 bucket to create"
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "^[a-z0-9.-]+$"
    ConstraintDescription: "must be between 3 and 63 characters and contain only lowercase letters, numbers, dots, and hyphens."
    Default: "basic-bucket"
Resources:
  BasicS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Ref BucketName
        - Key: TeamName
          Value: DevSecOps
  BasicS3BucketPolicy:
    Type: AWS::S3::ManagedPolicy
    Properties: 
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: ['s3:GetObject']
            Resource: !Sub arn:aws:s3:::${BasicS3Bucket}/*\

